"""add mixed emotional valence

Revision ID: 06aafb457714
Revises: 5f7d4ec19f92
Create Date: 2025-06-22 13:52:39.180586

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "06aafb457714"
down_revision = "5f7d4ec19f92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Since we're now using VARCHAR instead of ENUM, update the CHECK constraint
    op.drop_constraint('ck_log_fragments_emotional_valence', 'log_fragments')
    op.create_check_constraint(
        'ck_log_fragments_emotional_valence',
        'log_fragments',
        "emotional_valence IN ('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
