"""add mixed emotional valence

Revision ID: 06aafb457714
Revises: 5f7d4ec19f92
Create Date: 2025-06-22 13:52:39.180586

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "06aafb457714"
down_revision = "5f7d4ec19f92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL ENUM型への値追加はトランザクション内では実行できないため、
    # 別の接続で実行する必要がある
    op.execute("COMMIT")
    op.execute("ALTER TYPE emotionalvalence ADD VALUE 'MIXED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
