"""rename energy to mp in character_stats

Revision ID: 2bbcec8822fa
Revises: feb673044f6d
Create Date: 2025-07-06 15:06:10.869894

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "2bbcec8822fa"
down_revision = "feb673044f6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # カラムをリネーム（データを保持）
    op.alter_column("character_stats", "energy", new_column_name="mp")
    op.alter_column("character_stats", "max_energy", new_column_name="max_mp")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # カラムをリネーム（データを保持）
    op.alter_column("character_stats", "mp", new_column_name="energy")
    op.alter_column("character_stats", "max_mp", new_column_name="max_energy")
    # ### end Alembic commands ###
