"""Add story arc management system

Revision ID: 40d98dfeea22
Revises: dc7549876fcb
Create Date: 2025-07-08 09:32:37.733894

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40d98dfeea22'
down_revision = 'dc7549876fcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_arcs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('arc_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=False),
    sa.Column('total_phases', sa.Integer(), nullable=False),
    sa.Column('key_npcs', sa.JSON(), nullable=False),
    sa.Column('key_locations', sa.JSON(), nullable=False),
    sa.Column('key_items', sa.JSON(), nullable=False),
    sa.Column('central_conflict', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('plot_points', sa.JSON(), nullable=False),
    sa.Column('arc_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_arcs_character_id'), 'story_arcs', ['character_id'], unique=False)
    op.create_index(op.f('ix_story_arcs_id'), 'story_arcs', ['id'], unique=False)
    op.create_table('story_arc_milestones',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('story_arc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('achievement_criteria', sa.JSON(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rewards', sa.JSON(), nullable=False),
    sa.Column('triggers_next_phase', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_arc_id'], ['story_arcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_arc_milestones_id'), 'story_arc_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_story_arc_milestones_story_arc_id'), 'story_arc_milestones', ['story_arc_id'], unique=False)
    op.alter_column('character_exploration_progress', 'areas_explored',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('location_connections', 'path_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('location_connections', 'path_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location_connections', 'path_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=True)
    op.alter_column('location_connections', 'path_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               server_default=sa.text("'DIRECT'"),
               existing_nullable=False)
    op.alter_column('character_exploration_progress', 'areas_explored',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.drop_index(op.f('ix_story_arc_milestones_story_arc_id'), table_name='story_arc_milestones')
    op.drop_index(op.f('ix_story_arc_milestones_id'), table_name='story_arc_milestones')
    op.drop_table('story_arc_milestones')
    op.drop_index(op.f('ix_story_arcs_id'), table_name='story_arcs')
    op.drop_index(op.f('ix_story_arcs_character_id'), table_name='story_arcs')
    op.drop_table('story_arcs')
    # ### end Alembic commands ###