"""add new dispatch objective types

Revision ID: 4dce687c18a9
Revises: 06aafb457714
Create Date: 2025-06-22 14:26:52.332740

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4dce687c18a9'
down_revision = '06aafb457714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_reports', sa.Column('economic_details', sa.JSON(), nullable=True))
    op.add_column('dispatch_reports', sa.Column('special_achievements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_reports', 'special_achievements')
    op.drop_column('dispatch_reports', 'economic_details')
    # ### end Alembic commands ###
