"""Initial GESTALOKA schema

Revision ID: 52ba950d32b4
Revises:
Create Date: 2025-06-18 07:19:26.173682

"""

# revision identifiers, used by Alembic.
revision = "52ba950d32b4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
