"""add exploration fields to log fragments

Revision ID: 5f7d4ec19f92
Revises: 548c7fd6bf43
Create Date: 2025-06-22 13:49:17.618244

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "5f7d4ec19f92"
down_revision = "548c7fd6bf43"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log_fragments", sa.Column("keyword", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("log_fragments", sa.Column("backstory", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("log_fragments", sa.Column("discovered_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("log_fragments", sa.Column("source_action", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column("log_fragments", "session_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("log_fragments", "session_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("log_fragments", "source_action")
    op.drop_column("log_fragments", "discovered_at")
    op.drop_column("log_fragments", "backstory")
    op.drop_column("log_fragments", "keyword")
    # ### end Alembic commands ###
