"""Add foreign key constraint to story_arc_id in game_sessions

Revision ID: 860dcd753031
Revises: b00462ad802f
Create Date: 2025-07-08 10:10:35.739074

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "860dcd753031"
down_revision = "b00462ad802f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "game_sessions", "story_arcs", ["story_arc_id"], ["id"])
    # ENUMの変更は削除（既存のVARCHARのまま）
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "game_sessions", type_="foreignkey")
    # ### end Alembic commands ###
