"""Add story_arc_progress to session_results

Revision ID: b00462ad802f
Revises: 40d98dfeea22
Create Date: 2025-07-08 09:37:18.968054

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b00462ad802f"
down_revision = "40d98dfeea22"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session_results", sa.Column("story_arc_progress", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session_results", "story_arc_progress")
    # ### end Alembic commands ###
