"""Fix story arc types to use VARCHAR instead of ENUM

Revision ID: b9b93fc3808e
Revises: 860dcd753031
Create Date: 2025-07-08 10:55:49.043490

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b9b93fc3808e'
down_revision = '860dcd753031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if ENUMs exist and drop them if they do
    op.execute("""
        DO $$
        BEGIN
            -- Drop ENUM types if they exist
            DROP TYPE IF EXISTS storyarctype CASCADE;
            DROP TYPE IF EXISTS storyarcstatus CASCADE;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No downgrade needed as we're removing ENUMs
    pass
    # ### end Alembic commands ###

