"""Add session system redesign models with string types

Revision ID: bd0260bf1fd1
Revises: 2bbcec8822fa
Create Date: 2025-07-07 15:56:47.396075

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd0260bf1fd1'
down_revision = '2bbcec8822fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_messages_id'), 'game_messages', ['id'], unique=False)
    op.create_index(op.f('ix_game_messages_session_id'), 'game_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_game_messages_turn_number'), 'game_messages', ['turn_number'], unique=False)
    op.create_table('session_results',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('story_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_events', sa.JSON(), nullable=False),
    sa.Column('experience_gained', sa.Integer(), nullable=False),
    sa.Column('skills_improved', sa.JSON(), nullable=False),
    sa.Column('items_acquired', sa.JSON(), nullable=False),
    sa.Column('neo4j_updates', sa.JSON(), nullable=False),
    sa.Column('continuation_context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unresolved_plots', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_results_id'), 'session_results', ['id'], unique=False)
    op.create_index(op.f('ix_session_results_session_id'), 'session_results', ['session_id'], unique=True)
    op.add_column('game_sessions', sa.Column('session_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='active'))
    op.add_column('game_sessions', sa.Column('session_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('game_sessions', sa.Column('previous_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('game_sessions', sa.Column('story_arc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('game_sessions', sa.Column('result_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('game_sessions', sa.Column('result_processed_at', sa.DateTime(), nullable=True))
    op.add_column('game_sessions', sa.Column('turn_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('game_sessions', sa.Column('word_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('game_sessions', sa.Column('play_duration_minutes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('game_sessions', sa.Column('ending_proposal_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('game_sessions', sa.Column('last_proposal_at', sa.DateTime(), nullable=True))
    op.add_column('game_sessions', sa.Column('is_first_session', sa.Boolean(), nullable=False, server_default='false'))
    op.create_foreign_key('fk_game_sessions_previous_session_id', 'game_sessions', 'game_sessions', ['previous_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_game_sessions_previous_session_id', 'game_sessions', type_='foreignkey')
    op.drop_column('game_sessions', 'is_first_session')
    op.drop_column('game_sessions', 'last_proposal_at')
    op.drop_column('game_sessions', 'ending_proposal_count')
    op.drop_column('game_sessions', 'play_duration_minutes')
    op.drop_column('game_sessions', 'word_count')
    op.drop_column('game_sessions', 'turn_count')
    op.drop_column('game_sessions', 'result_processed_at')
    op.drop_column('game_sessions', 'result_summary')
    op.drop_column('game_sessions', 'story_arc_id')
    op.drop_column('game_sessions', 'previous_session_id')
    op.drop_column('game_sessions', 'session_number')
    op.drop_column('game_sessions', 'session_status')
    op.drop_index(op.f('ix_session_results_session_id'), table_name='session_results')
    op.drop_index(op.f('ix_session_results_id'), table_name='session_results')
    op.drop_table('session_results')
    op.drop_index(op.f('ix_game_messages_turn_number'), table_name='game_messages')
    op.drop_index(op.f('ix_game_messages_session_id'), table_name='game_messages')
    op.drop_index(op.f('ix_game_messages_id'), table_name='game_messages')
    op.drop_table('game_messages')
    # ### end Alembic commands ###
