"""Add current_location and last_location_update to LogDispatch

Revision ID: c1e62d1312f8
Revises: 4dce687c18a9
Create Date: 2025-06-28 20:12:09.392038

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c1e62d1312f8'
down_revision = '4dce687c18a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_dispatches', sa.Column('current_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('log_dispatches', sa.Column('last_location_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_dispatches', 'last_location_update')
    op.drop_column('log_dispatches', 'current_location')
    # ### end Alembic commands ###
