"""Add character limits to quest title/description fields

Revision ID: cb687f3e2cde
Revises: cc266dcfc3c1
Create Date: 2025-07-06 13:46:41.695030

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'cb687f3e2cde'
down_revision = 'cc266dcfc3c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quests', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('quests', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quests', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('quests', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
