"""Add compilation bonus system and metadata to completed logs

Revision ID: cc266dcfc3c1
Revises: 1767f598eb6e
Create Date: 2025-07-04 09:31:39.007377

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc266dcfc3c1"
down_revision = "1767f598eb6e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("completed_logs", sa.Column("compilation_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("completed_logs", "compilation_metadata")
    # ### end Alembic commands ###
