"""Add SP purchase system

Revision ID: d7021f88ea80
Revises: c1e62d1312f8
Create Date: 2025-06-29 11:37:34.942431

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "d7021f88ea80"
down_revision = "c1e62d1312f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sp_purchases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plan_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sp_amount", sa.Integer(), nullable=False),
        sa.Column("price_jpy", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED", "REFUNDED", name="purchasestatus"),
            nullable=False,
        ),
        sa.Column("payment_mode", sa.Enum("TEST", "PRODUCTION", name="paymentmode"), nullable=False),
        sa.Column("test_reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("stripe_payment_intent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stripe_checkout_session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sp_purchases_plan_id"), "sp_purchases", ["plan_id"], unique=False)
    op.create_index(op.f("ix_sp_purchases_user_id"), "sp_purchases", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sp_purchases_user_id"), table_name="sp_purchases")
    op.drop_index(op.f("ix_sp_purchases_plan_id"), table_name="sp_purchases")
    op.drop_table("sp_purchases")
    # ### end Alembic commands ###
