"""add_keyword_field_to_log_fragments

Revision ID: dc7549876fcb
Revises: bd0260bf1fd1
Create Date: 2025-07-07 23:10:05.173077

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'dc7549876fcb'
down_revision = 'bd0260bf1fd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'session_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'session_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'turn_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'play_duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'ending_proposal_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'is_first_session',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'is_first_session',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'ending_proposal_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'play_duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'turn_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'session_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'session_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
