"""Update quest description limit to 2500 chars

Revision ID: feb673044f6d
Revises: cb687f3e2cde
Create Date: 2025-07-06 13:54:18.904905

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'feb673044f6d'
down_revision = 'cb687f3e2cde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quests', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quests', 'description',
               existing_type=sa.String(length=2500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
